### ISSUE TITLE
Missing current and voltage attributes in v3

### ISSUE THREAD

**Issue by mschulze46** [radical-squared/aquatemp#45]
**Is your feature request related to a problem? Please describe.**
I just upgraded from v2 to v3 and now missing the current and voltage in order to calculate the energy consumption.

**Describe the solution you'd like**
In v2 I could extract the attributes from the aquatemp entity.

**Additional context**
I extracted the attributes from the aquatemp entity in v2 via templates as following:

``` yaml
# Current
- sensor:
  - name: "Pool Heat Pump: Current"
    icon: mdi:lightning-bolt
    unit_of_measurement: 'A'
    state: >-
      {{ state_attr('climate.aquatemp', 'codes')[26].value }}
    state_class: measurement
    device_class: current

# Voltage
- sensor:
  - name: "Pool Heat Pump: Voltage"
    icon: mdi:lightning-bolt
    unit_of_measurement: 'V'
    state: >-
      {{ state_attr('climate.aquatemp', 'codes')[28].value }}
    state_class: measurement
    device_class: voltage

# Current Consumption
- sensor:
  - name: "Pool Heat Pump: Current Consumption"
    icon: mdi:lightning-bolt
    unit_of_measurement: 'W'
    state: >-
      {{ (state_attr('climate.aquatemp', 'codes')[28].value|float) * (state_attr('climate.aquatemp', 'codes')[26].value|float) }}
    state_class: measurement
    device_class: power
```

Many thanks for your superb effort!!!
